-- Tabela de uploads do EMP
CREATE TABLE IF NOT EXISTS emp_uploads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    output_filename VARCHAR(255),
    data_arquivo DATETIME NULL,
    uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela principal com registros tratados do EMP
CREATE TABLE IF NOT EXISTS emp (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    upload_id BIGINT NULL,
    chave VARCHAR(255),
    chave_planejamento VARCHAR(255),
    regiao VARCHAR(255),
    subfuncao_ug VARCHAR(255),
    adj VARCHAR(255),
    macropolitica VARCHAR(255),
    pilar VARCHAR(255),
    eixo VARCHAR(255),
    politica_decreto VARCHAR(255),
    exercicio VARCHAR(50),
    situacao VARCHAR(255),
    historico TEXT,
    numero_emp VARCHAR(100),
    numero_ped VARCHAR(100),
    numero_contrato VARCHAR(100),
    numero_convenio VARCHAR(100),
    dotacao_orcamentaria VARCHAR(255),
    funcao VARCHAR(255),
    subfuncao VARCHAR(255),
    programa_governo VARCHAR(255),
    paoe VARCHAR(255),
    natureza_despesa VARCHAR(255),
    cat_econ VARCHAR(50),
    grupo VARCHAR(50),
    modalidade VARCHAR(50),
    fonte VARCHAR(50),
    iduso VARCHAR(50),
    elemento VARCHAR(100),
    uo VARCHAR(100),
    nome_unidade_orcamentaria VARCHAR(255),
    ug VARCHAR(100),
    nome_unidade_gestora VARCHAR(255),
    data_emissao DATETIME NULL,
    data_criacao DATETIME NULL,
    valor_emp DECIMAL(18, 2) NULL,
    devolucao_gcv DECIMAL(18, 2) NULL,
    valor_emp_devolucao_gcv DECIMAL(18, 2) NULL,
    tipo_empenho VARCHAR(100),
    tipo_despesa VARCHAR(255),
    credor VARCHAR(255),
    nome_credor VARCHAR(255),
    cpf_cnpj_credor VARCHAR(50),
    categoria_credor VARCHAR(100),
    raw_payload LONGTEXT,
    data_atualizacao DATETIME NULL,
    data_arquivo DATETIME NULL,
    user_email VARCHAR(255),
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_emp_upload (upload_id),
    INDEX idx_emp_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
