-- Tabela de uploads do PED
CREATE TABLE IF NOT EXISTS ped_uploads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    output_filename VARCHAR(255),
    data_arquivo DATETIME NULL,
    uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabela principal com registros tratados do PED
CREATE TABLE IF NOT EXISTS ped (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    upload_id BIGINT NULL,
    chave VARCHAR(255),
    regiao VARCHAR(255),
    subfuncao_ug VARCHAR(255),
    adj VARCHAR(255),
    macropolitica VARCHAR(255),
    pilar VARCHAR(255),
    eixo VARCHAR(255),
    politica_decreto VARCHAR(255),
    exercicio VARCHAR(50),
    historico TEXT,
    numero_ped VARCHAR(100),
    numero_ped_estorno VARCHAR(100),
    numero_emp VARCHAR(100),
    numero_cad VARCHAR(100),
    numero_noblist VARCHAR(100),
    numero_os VARCHAR(100),
    convenio VARCHAR(255),
    numero_processo_orcamentario_pagamento VARCHAR(255),
    indicativo_licitacao_exercicios_anteriores VARCHAR(255),
    liberado_fisco_estadual VARCHAR(255),
    situacao VARCHAR(255),
    uo VARCHAR(100),
    nome_unidade_orcamentaria VARCHAR(255),
    ug VARCHAR(100),
    nome_unidade_gestora VARCHAR(255),
    dotacao_orcamentaria VARCHAR(255),
    funcao VARCHAR(255),
    subfuncao VARCHAR(255),
    programa_governo VARCHAR(255),
    paoe VARCHAR(255),
    natureza_despesa VARCHAR(255),
    cat_econ VARCHAR(50),
    grupo VARCHAR(50),
    modalidade VARCHAR(50),
    fonte VARCHAR(50),
    iduso VARCHAR(50),
    elemento VARCHAR(100),
    nome_elemento VARCHAR(255),
    numero_emenda_ep VARCHAR(100),
    autor_emenda_ep VARCHAR(255),
    numero_cac VARCHAR(100),
    licitacao VARCHAR(255),
    usuario_responsavel VARCHAR(255),
    data_solicitacao VARCHAR(50),
    data_criacao VARCHAR(50),
    data_autorizacao VARCHAR(50),
    data_licitacao VARCHAR(50),
    data_hora_cadastro_autorizacao VARCHAR(50),
    tipo_empenho VARCHAR(100),
    tipo_despesa VARCHAR(255),
    numero_abj VARCHAR(100),
    numero_processo_sequestro_judicial VARCHAR(255),
    indicativo_entrega_imediata VARCHAR(255),
    indicativo_contrato VARCHAR(255),
    codigo_uo_extinta VARCHAR(100),
    devolucao_gcv VARCHAR(255),
    mes_competencia_folha_pagamento VARCHAR(50),
    exercicio_competencia_folha VARCHAR(50),
    obrigacao_patronal VARCHAR(255),
    tipo_obrigacao_patronal VARCHAR(255),
    numero_nla VARCHAR(100),
    valor_ped VARCHAR(50),
    valor_estorno VARCHAR(50),
    credor VARCHAR(255),
    nome_credor VARCHAR(255),
    chave_planejamento VARCHAR(255),
    data_atualizacao DATETIME NULL,
    data_arquivo DATETIME NULL,
    user_email VARCHAR(255),
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ped_upload (upload_id),
    INDEX idx_ped_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
